# Generated by Django 5.2.1 on 2025-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('store', 'Store')], default='member', max_length=10),
        ),
    ]
