# Generated by Django 5.2 on 2025-05-09 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_calories_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="calories",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator("0")],
            ),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.PositiveIntegerField(),
        ),
    ]
