# Generated by Django 5.2 on 2025-05-09 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_calories_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator("0")],
            ),
        ),
    ]
