# Generated by Django 5.2 on 2025-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="calories", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.PositiveIntegerField(),
        ),
    ]
