INVALID_NEGATIVE_MSG = 'Ensure this value is greater than or equal to 0.'
INVALID_PHONE_MSG = '手機號碼格式錯誤'
INVALID_GENDER_MSG = 'is not a valid choice'
INVALID_TAX_ID_MSG = '統編必須為8位數字'
INVALID_EMAIL_MSG = ''
INVALID_PASSWORD_MSG = ''
