# Generated by Django 5.2 on 2025-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_hours',
            field=models.CharField(default='09:00-18:00', max_length=50),
        ),
    ]
