# Generated by Django 5.2 on 2025-05-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default='06:00'),
        ),
    ]
