# Generated by Django 5.2 on 2025-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_business_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default='06:00'),
        ),
    ]
