# Generated by Django 5.2 on 2025-05-03 19:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_time', models.DateTimeField()),
                ('note', models.TextField()),
                ('order_status', models.CharField(default='pending', max_length=5)),
                ('payment_method', models.CharField(max_length=10)),
                ('payment_status', models.CharField(default='unpaid', max_length=5)),
                ('total_price', models.PositiveIntegerField()),
                ('customize', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
