# Generated by Django 5.2 on 2025-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_completed_at_order_member_order_member_name_and_more'),
        ('products', '0007_alter_product_calories_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='ordered_in', through='orders.OrderItem', to='products.product'),
        ),
    ]
