# Generated by Django 5.2 on 2025-05-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customize_alter_order_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oder',
            new_name='order',
        ),
    ]
