# Generated by Django 5.2 on 2025-05-05 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '不提供')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('line_id', models.CharField(blank=True, max_length=64, null=True)),
                ('google_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
