# Generated by Django 5.2 on 2025-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_phone_number'),
        ('orders', '0002_order_completed_at_order_member_order_member_name_and_more'),
        ('stores', '0002_store_closing_time_store_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ordered_stores',
            field=models.ManyToManyField(related_name='ordering_members', through='orders.Order', to='stores.store'),
        ),
    ]
