# Generated by Django 5.2.1 on 2025-05-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_ordered_stores'),
        ('members', '0004_alter_member_name'),
    ]

    operations = [
    ]
