# Generated by Django 5.2.1 on 2025-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_merge_20250516_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '不提供')], max_length=10, null=True),
        ),
    ]
