# Generated by Django 5.2 on 2025-05-09 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="calories",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="customize",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product", name="quantity", field=models.PositiveIntegerField(),
        ),
    ]
