# Generated by Django 5.2 on 2025-05-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_calories_alter_product_price'),
        ('stores', '0002_store_closing_time_store_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default='1d784244-6de0-4b79-aef8-07a01d906873', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
            preserve_default=False,
        ),
    ]
